server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:certs/bff-web.p12
    key-store-password: changeit
    key-store-type: PKCS12
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
spring:
  main:
    banner-mode: "off"
security:
  jwt:
    secret: "super-secret-web-key-32-bytes-super-secret-web-key"
